feat(meta): add disallowApplyAll options
zhaofengli/colmena pull request #96
Opened 2022-06-18 07:08 UTC by NeverBehave

related https://github.com/zhaofengli/colmena/issues/95

This PR also add metaConfig struct for `hive.meta` section.

2022-06-18 12:01 UTC, otavio requested changes

2022-06-20 23:21 UTC, zhaofengli reviewed
Could you also add a changelog entry in `manual/src/release-notes.md`? Please squash the last two commits as well.

2022-06-20 23:21 UTC, zhaofengli commented on src/nix/hive/options.nix
> +      disallowApplyAll = lib.mkOption {
I think we should change it to `allowApplyAll` just to be consistent with `allowLocalDeployment`.

2022-06-21 02:24 UTC, zhaofengli commented
Thanks!

2022-06-21 02:24 UTC, merged